#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    pot_fourbar_left, sensorPotentiometer)
#pragma config(Sensor, in2,    pot_fourbar_right, sensorPotentiometer)
#pragma config(Sensor, in3,    pot_chainbar,   sensorPotentiometer)
#pragma config(Sensor, in5,    pot_mb,         sensorPotentiometer)
#pragma config(Sensor, in6,    gyro_right,     sensorGyro)
#pragma config(Sensor, in7,    gyro_left,      sensorGyro)
#pragma config(Sensor, dgtl1,  en_front_left,  sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  en_front_right, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  en_back_left,   sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  en_back_right,  sensorQuadEncoder)
#pragma config(Motor,  port1,           mb,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           front_left,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           front_right,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           fb_left,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           fb_right,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           chainbar_right,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           chainbar_left,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           back_left,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           back_right,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,           roller,    tmotorVex393_MC29, openLoop, reversed)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define ever ;;
#include "Driver.h"
#include "autonomousHelpers.h"
int lastBatteryLevel=nImmediateBatteryLevel;


task main()
{
	while(true){
		if(vexRT[Btn7L]){
			clearTimer(T4);
			clearDebugStream();
			while (nImmediateBatteryLevel>7500){

				clearTimer(T1);
				resetEncoders();
				while (time1(T1)<1000){
					moveLeftWheels(127);
					moveRightWheels(127);
				}
				moveLeftWheels(0);
				moveRightWheels(0);
				writeDebugStreamLine("%f,%f,%f",nImmediateBatteryLevel/1000.0,
				(-SensorValue(en_back_left)+SensorValue(en_front_left)+SensorValue(en_back_right)+SensorValue(en_front_right))/4/(360/(4*PI)),time1(T4)/1000.0);
				wait1Msec(1000);
				clearTimer(T1);
				resetEncoders();
				while (time1(T1)<1000){
					moveLeftWheels(-127);
					moveRightWheels(-127);
				}
				moveLeftWheels(0);
				moveRightWheels(0);
				writeDebugStreamLine("%f,%f,%f",nImmediateBatteryLevel/1000.0,
				(-SensorValue(en_back_left)+SensorValue(en_front_left)+SensorValue(en_back_right)+SensorValue(en_front_right))/4/(360/(4*PI)),time1(T4)/1000.0);
				wait1Msec(1000);
			}
		}
}}
