#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    pot_lift_left,  sensorPotentiometer)
#pragma config(Sensor, in2,    pot_fourbar_left, sensorPotentiometer)
#pragma config(Sensor, in3,    pot_lift_right, sensorPotentiometer)
#pragma config(Sensor, in4,    pot_fourbar_right, sensorPotentiometer)
#pragma config(Sensor, in5,    pot_mg,         sensorPotentiometer)
#pragma config(Sensor, in6,    gyro_right,     sensorGyro)
#pragma config(Sensor, in7,    gyro_left,      sensorGyro)
#pragma config(Sensor, in8,    acc,            sensorNone)
#pragma config(Sensor, dgtl1,  en_left_base,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  en_right_base,  sensorQuadEncoder)
#pragma config(Motor,  port1,           mg,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           left_fourbar,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           left_lift_1,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           right_lift_1,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           left_base,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           right_base,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           left_lift_2,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           right_lift_2,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           right_fourbar, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          roller,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define ever ;;
#include "Driver.h"
#include "autonomousHelpers.h"

task main()
{
//#include "Autonomous.h"
//startTask(WheelControls);

for(ever){
if (vexRT[Btn7L]){
	stopTask(WheelControls);clearDebugStream();writeDebugStreamLine("Start of the log");
moveWheels(12,true);
}
else if (vexRT[Btn7R]){stopTask(WheelControls);clearDebugStream();writeDebugStreamLine("Start of the log");
moveWheels(24,true);
}
else if (vexRT[Btn8L]){stopTask(WheelControls);clearDebugStream();writeDebugStreamLine("Start of the log");
moveWheels(36,true);
}
else if (vexRT[Btn8R]){stopTask(WheelControls);clearDebugStream();writeDebugStreamLine("Start of the log");
moveWheels(48,true);
}

else if (vexRT[Btn7U]){stopTask(WheelControls);clearDebugStream();writeDebugStreamLine("Start of the log");
	moveWheels(-12,true);
}
else if (vexRT[Btn8U]){stopTask(WheelControls);clearDebugStream();writeDebugStreamLine("Start of the log");
	moveWheels(-24,true);
}
else if (vexRT[Btn7D]){stopTask(WheelControls);clearDebugStream();writeDebugStreamLine("Start of the log");
	moveWheels(-36,true);
}
else if (vexRT[Btn8D]){stopTask(WheelControls);clearDebugStream();writeDebugStreamLine("Start of the log");
	moveWheels(-48,true);
}
else if (vexRT[Btn5U]){stopTask(WheelControls);clearDebugStream();writeDebugStreamLine("Start of the log");
	turn(45);
}
else if (vexRT[Btn5D]){stopTask(WheelControls);clearDebugStream();writeDebugStreamLine("Start of the log");
	turn(90);
}

else if (vexRT[Btn6U]){stopTask(WheelControls);clearDebugStream();writeDebugStreamLine("Start of the log");
	turn(-45);
}

else if (vexRT[Btn6D]){stopTask(WheelControls);clearDebugStream();writeDebugStreamLine("Start of the log");
	turn(-90);
}
else {
	if (vexRT[Ch2]>10|vexRT[Ch3]>10){
	releaseWheels();
	startTask(WheelControls);
}
	}

}
}
