#pragma config(Sensor, dgtl2,  ,               sensorQuadEncoder)
#pragma config(Motor,  port1,           mb_left,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           front_left,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           front_right,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           fb_left,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           fb_right,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           roller,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           chainbar,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           back_left,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           back_right,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          mb_right,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Driver.h"

task main
{
//#include "UserControls.h"

startTask (WheelControls);
startTask (MobileGoalControls);
startTask (FourBarControls);
startTask (RollerControls);
startTask (ChainBarControls);
for(;;){}

}
